export type SourceStatus =
  | "official_current"
  | "official_historical"
  | "official_future"
  | "official_notice"
  | "access_restricted"
  | "not_verified";

export type SourceRecord = {
  id: string;
  title: string;
  publisher: string;
  url: string;
  documentType: string;
  publicationDate: string;
  lastVerified: string;
  status: SourceStatus;
  language: string;
  topics: string[];
  pages?: number;
  official: boolean;
  priority: "tier1" | "tier2" | "tier3";
  parsed: boolean;
  contentHash: string;
  notes?: string;
};

export type EvidenceRecord = {
  id: string;
  sourceId: string;
  page: string;
  section: string;
  claim: string;
  topic: string;
  effectiveDate?: string;
  confidence: "high" | "medium";
};

export type KnowledgeScenario = {
  title: string;
  happened: string;
  why: string;
  officialGuidance: string;
  nextStep: string;
};

export type KnowledgeLesson = {
  id: string;
  moduleId: string;
  title: string;
  summary: string;
  whatYouNeedToKnow: string[];
  officialProcedure: string[];
  terminology: string[];
  commonMistake: string;
  scenario?: KnowledgeScenario;
  sourceIds: string[];
  evidenceIds: string[];
  lastVerified: string;
  status: SourceStatus;
};

export type KnowledgeModule = {
  id: string;
  number: string;
  title: string;
  description: string;
  status: SourceStatus;
  sourceIds: string[];
  lessonIds: string[];
};

export type KnowledgeGlossaryEntry = {
  term: string;
  meaning: string;
  explanation: string;
  example: string;
  sourceLabel: string;
  sourceIds: string[];
  evidenceId: string;
};

export type KnowledgeQuestion = {
  id: string;
  category: string;
  finnish: string;
  arabic: string;
  options: string[];
  answer: number;
  explanation: string;
  source: string;
  sourcePage: string;
  evidenceId: string;
  trainingQuestion: true;
  officialExamQuestion: false;
};

const verifiedOn = "2026-08-18";

export const sourceRegistry: SourceRecord[] = [
  {
    id: "th-training",
    title: "Taksi Helsingin kuljettajakoulutus",
    publisher: "Taksi Helsinki",
    url: "https://taksihelsinki.fi/taksi-helsinki/taksi-helsingin-kuljettajakoulutus/",
    documentType: "official web page",
    publicationDate: "Not stated on page",
    lastVerified: verifiedOn,
    status: "official_current",
    language: "Finnish",
    topics: ["driver path", "training", "Koulutusajo", "special groups"],
    official: true,
    priority: "tier1",
    parsed: true,
    contentHash: "not_computed_in_static_build",
    notes: "Public training page. Training details can change; the source link remains authoritative.",
  },
  {
    id: "traficom-licence",
    title: "Apply for a taxi driving licence",
    publisher: "Traficom",
    url: "https://traficom.fi/en/commercial-transport/drivers-licenses-and-qualifications/apply-taxi-driving-licence",
    documentType: "official web page",
    publicationDate: "2026-08-05",
    lastVerified: verifiedOn,
    status: "official_current",
    language: "English",
    topics: ["licence", "exam", "health", "Ajovarma"],
    official: true,
    priority: "tier3",
    parsed: true,
    contentHash: "not_computed_in_static_build",
  },
  {
    id: "traficom-reform",
    title: "Changes to taxi transport regulation",
    publisher: "Traficom",
    url: "https://traficom.fi/en/commercial-transport/changes-taxi-transport-regulation",
    documentType: "official future-change page",
    publicationDate: "2026-08-03",
    lastVerified: verifiedOn,
    status: "official_future",
    language: "English",
    topics: ["future law", "taximeter", "taxi plates", "fare transparency"],
    official: true,
    priority: "tier3",
    parsed: true,
    contentHash: "not_computed_in_static_build",
    notes: "Future dates are deliberately not presented as current rules.",
  },
  {
    id: "kela-transport",
    title: "Transport by taxi",
    publisher: "Kela",
    url: "https://www.kela.fi/transport-by-taxi",
    documentType: "official web page",
    publicationDate: "Not stated on page",
    lastVerified: verifiedOn,
    status: "official_current",
    language: "English",
    topics: ["Kela", "regional dispatch", "special needs", "familiar driver"],
    official: true,
    priority: "tier2",
    parsed: true,
    contentHash: "not_computed_in_static_build",
  },
  {
    id: "th-kela",
    title: "Kela-taxi",
    publisher: "Taksi Helsinki",
    url: "https://taksihelsinki.fi/en/kela-taxi/",
    documentType: "official web page",
    publicationDate: "Not stated on page",
    lastVerified: verifiedOn,
    status: "official_current",
    language: "English",
    topics: ["Kela", "driver training", "service"],
    official: true,
    priority: "tier1",
    parsed: true,
    contentHash: "not_computed_in_static_build",
  },
  {
    id: "th-kela-autot",
    title: "Kela-autot — operator and driver services",
    publisher: "Taksi Helsinki",
    url: "https://taksihelsinki.fi/autoilija-ja-kuljettajapalvelut/kela-autot/",
    documentType: "official web page",
    publicationDate: "Not stated on page",
    lastVerified: verifiedOn,
    status: "official_current",
    language: "Finnish",
    topics: ["Kela", "Ahola Digital", "dispatch terminal", "meters", "regions", "driver requirements"],
    official: true,
    priority: "tier1",
    parsed: true,
    contentHash: "not_computed_in_static_build",
    notes: "The page contains both the current contract through 31.12.2026 and a separately dated 2027 contract section; effective dates are kept on the evidence records.",
  },
  {
    id: "th-front",
    title: "Taksi Helsinki official front page",
    publisher: "Taksi Helsinki",
    url: "https://taksihelsinki.fi/en/frontpage/",
    documentType: "official web page",
    publicationDate: "Not stated on page",
    lastVerified: verifiedOn,
    status: "official_current",
    language: "English",
    topics: ["service quality", "service area", "driver permit"],
    official: true,
    priority: "tier1",
    parsed: true,
    contentHash: "not_computed_in_static_build",
  },
  {
    id: "th-ad-sote-2026",
    title: "Kuljettajaohje 02.02.2026 — AD Kuljettaja, Kuljettajan ajosovellus SOTE",
    publisher: "Taksi Helsinki",
    url: "https://taksihelsinki.fi/app/uploads/2026/02/Kuljettajaohje_02022026.pdf",
    documentType: "official PDF",
    publicationDate: "2026-02-02",
    lastVerified: verifiedOn,
    status: "official_current",
    language: "Finnish",
    topics: ["AD Kuljettaja", "work shift", "offers", "trip states", "open list", "ruudut", "troubleshooting"],
    pages: 20,
    official: true,
    priority: "tier1",
    parsed: true,
    contentHash: "not_computed_in_static_build",
    notes: "This is the current public SOTE driver guide found during source discovery; it is not an Autocab guide.",
  },
  {
    id: "th-ad-kela-2024",
    title: "AD Kuljettaja — Kuljettajan ajosovellus KELA",
    publisher: "Taksi Helsinki",
    url: "https://taksihelsinki.fi/app/uploads/2025/06/kela-kuljettajasovellus-03102024.pdf",
    documentType: "official PDF",
    publicationDate: "2024-10-03 (filename date; uploaded 2025-06-19)",
    lastVerified: verifiedOn,
    status: "official_historical",
    language: "Finnish",
    topics: ["AD Kuljettaja", "Kela", "trip states", "notifications", "meter data"],
    pages: 18,
    official: true,
    priority: "tier1",
    parsed: true,
    contentHash: "not_computed_in_static_build",
    notes: "Retained for historical Kela workflow evidence; verify against the current Kela instructions before operational use.",
  },
  {
    id: "th-quality-commitment",
    title: "Liite 3: Kuljettajan laatusitoumus",
    publisher: "Taksi Helsinki",
    url: "https://taksihelsinki.fi/app/uploads/2025/06/Liite-3_Kuljettajan-laatusitoumus.pdf",
    documentType: "official PDF",
    publicationDate: "2025-06-21",
    lastVerified: verifiedOn,
    status: "official_current",
    language: "Finnish",
    topics: ["quality", "customer service", "clothing", "privacy", "payments", "route"],
    pages: 6,
    official: true,
    priority: "tier1",
    parsed: true,
    contentHash: "not_computed_in_static_build",
  },
  {
    id: "th-materials",
    title: "Materiaalisalkku — driver materials entry point",
    publisher: "Taksi Helsinki",
    url: "https://taksihelsinki.fi/materiaalisalkku/",
    documentType: "official extranet entry point",
    publicationDate: "Not public",
    lastVerified: verifiedOn,
    status: "access_restricted",
    language: "Finnish",
    topics: ["Materiaalisalkku", "driver instructions", "Autocab", "Cabman", "Kela"],
    official: true,
    priority: "tier1",
    parsed: false,
    contentHash: "not_computed_in_static_build",
    notes: "The official page redirects to an Extranet login. No restricted material was accessed or bypassed.",
  },
  {
    id: "th-driver-notices",
    title: "Kuljettajatiedotteet — driver notices",
    publisher: "Taksi Helsinki",
    url: "https://taksihelsinki.fi/kuljettajatiedotteet/",
    documentType: "official notice archive entry point",
    publicationDate: "Not public",
    lastVerified: verifiedOn,
    status: "access_restricted",
    language: "Finnish",
    topics: ["official notices", "updates", "driver communications"],
    official: true,
    priority: "tier1",
    parsed: false,
    contentHash: "not_computed_in_static_build",
    notes: "The public URL redirects to Extranet login; no notices are represented as current facts.",
  },
  {
    id: "th-services-drivers",
    title: "Palvelut autoilijoille — services for operators",
    publisher: "Taksi Helsinki",
    url: "https://taksihelsinki.fi/palvelut-autoilijoille/",
    documentType: "official web page",
    publicationDate: "Not stated on page",
    lastVerified: verifiedOn,
    status: "official_current",
    language: "Finnish",
    topics: ["Cabman MDT", "dispatch device", "vehicle", "Kela connection", "taxi stand"],
    official: true,
    priority: "tier1",
    parsed: true,
    contentHash: "not_computed_in_static_build",
    notes: "The page confirms linked service categories; detailed order forms and restricted instructions are not converted into lessons.",
  },
  {
    id: "th-app-guide",
    title: "Taksi Helsinki -sovellusohjeet",
    publisher: "Taksi Helsinki",
    url: "https://taksihelsinki.fi/taksi-helsinki-sovellus/taksi-helsinki-sovellusohjeet/",
    documentType: "official web page",
    publicationDate: "Not stated on page",
    lastVerified: verifiedOn,
    status: "official_current",
    language: "Finnish",
    topics: ["customer app", "pricing display", "payments", "eKuitti", "pickup"],
    official: true,
    priority: "tier1",
    parsed: true,
    contentHash: "not_computed_in_static_build",
    notes: "This is a customer application guide, not a driver-system manual.",
  },
  {
    id: "th-mitax-300",
    title: "Kela-ohjeet Mitax 300",
    publisher: "Taksi Helsinki",
    url: "https://taksihelsinki.fi/app/uploads/2025/06/mitax-300_Kela.pdf",
    documentType: "official PDF",
    publicationDate: "Uploaded 2025-06-19",
    lastVerified: verifiedOn,
    status: "official_current",
    language: "Finnish",
    topics: ["Mitax 300", "meter", "Kela"],
    pages: 5,
    official: true,
    priority: "tier1",
    parsed: false,
    contentHash: "not_computed_in_static_build",
    notes: "The public text extraction exposed the title and page count only; no button-level claim is used.",
  },
  {
    id: "th-mitax-400",
    title: "Kela-ohjeet Mitax 400",
    publisher: "Taksi Helsinki",
    url: "https://taksihelsinki.fi/app/uploads/2025/06/Mitax-400_Kela.pdf",
    documentType: "official PDF",
    publicationDate: "Uploaded 2025-06-19",
    lastVerified: verifiedOn,
    status: "official_current",
    language: "Finnish",
    topics: ["Mitax 400", "meter", "Kela"],
    pages: 5,
    official: true,
    priority: "tier1",
    parsed: false,
    contentHash: "not_computed_in_static_build",
    notes: "The public text extraction exposed the title and page count only; no button-level claim is used.",
  },
  {
    id: "th-semel-m2",
    title: "Semel M2 — Kela",
    publisher: "Taksi Helsinki",
    url: "https://taksihelsinki.fi/app/uploads/2025/06/semel-m2_Kela.pdf",
    documentType: "official PDF",
    publicationDate: "Uploaded 2025-06-19",
    lastVerified: verifiedOn,
    status: "official_current",
    language: "Finnish",
    topics: ["Semel M2", "meter", "Kela"],
    pages: 7,
    official: true,
    priority: "tier1",
    parsed: false,
    contentHash: "not_computed_in_static_build",
    notes: "The public text extraction exposed the title and page count only; no button-level claim is used.",
  },
  {
    id: "th-kela-service-description-2022",
    title: "Kela Palvelukuvaus 2022",
    publisher: "Taksi Helsinki / Kela procurement material",
    url: "https://taksihelsinki.fi/app/uploads/2025/11/Kela_Palvelukuvaus_2022.pdf",
    documentType: "official historical PDF",
    publicationDate: "2021–2022 service period",
    lastVerified: verifiedOn,
    status: "official_historical",
    language: "Finnish",
    topics: ["Kela", "dispatch", "TAKSO", "historical contract", "data protection"],
    pages: 109,
    official: true,
    priority: "tier2",
    parsed: true,
    contentHash: "not_computed_in_static_build",
    notes: "This long procurement/service description is historical. It is never presented as the current 2026 operating rule.",
  },
  {
    id: "th-kela-2027",
    title: "Kela — new contract period",
    publisher: "Taksi Helsinki",
    url: "https://taksihelsinki.fi/autoilija-ja-kuljettajapalvelut/kela-autot-uusi-sopimuskausi/",
    documentType: "official future-information page",
    publicationDate: "Not stated on page",
    lastVerified: verifiedOn,
    status: "official_future",
    language: "Finnish",
    topics: ["Kela", "2027 contract", "future"],
    official: true,
    priority: "tier1",
    parsed: true,
    contentHash: "not_computed_in_static_build",
    notes: "Future-contract content is separated from current driver guidance.",
  },
  {
    id: "th-airport",
    title: "Toiminta lentoasemalla",
    publisher: "Taksi Helsinki",
    url: "https://taksihelsinki.fi/toiminta-lentoasemalla/",
    documentType: "official web page",
    publicationDate: "Not stated on page",
    lastVerified: verifiedOn,
    status: "official_current",
    language: "Finnish",
    topics: ["airport"],
    official: true,
    priority: "tier1",
    parsed: false,
    contentHash: "not_computed_in_static_build",
    notes: "The page was discovered, but no driver-only airport queue instruction is asserted without a readable public guide.",
  },
  {
    id: "th-ports",
    title: "Toiminta satamissa",
    publisher: "Taksi Helsinki",
    url: "https://taksihelsinki.fi/toiminta-satamissa/",
    documentType: "official web page",
    publicationDate: "Not stated on page",
    lastVerified: verifiedOn,
    status: "official_current",
    language: "Finnish",
    topics: ["ports"],
    official: true,
    priority: "tier1",
    parsed: false,
    contentHash: "not_computed_in_static_build",
    notes: "The page was discovered, but no current driver-only port procedure is asserted here.",
  },
  {
    id: "th-pricing",
    title: "Taksin hinta",
    publisher: "Taksi Helsinki",
    url: "https://taksihelsinki.fi/tilaa-taksi/taksin-hinta/",
    documentType: "official web page",
    publicationDate: "Not stated on page",
    lastVerified: verifiedOn,
    status: "official_current",
    language: "Finnish",
    topics: ["pricing", "fare"],
    official: true,
    priority: "tier1",
    parsed: false,
    contentHash: "not_computed_in_static_build",
    notes: "The app links to the live fare page rather than copying changeable prices into the static knowledge base.",
  },
  {
    id: "th-taxi-stands",
    title: "Taksiasemat",
    publisher: "Taksi Helsinki",
    url: "https://taksihelsinki.fi/tilaa-taksi/taksiasemat/",
    documentType: "official web page",
    publicationDate: "Not stated on page",
    lastVerified: verifiedOn,
    status: "official_current",
    language: "Finnish",
    topics: ["taxi stands", "local knowledge"],
    official: true,
    priority: "tier1",
    parsed: false,
    contentHash: "not_computed_in_static_build",
    notes: "Stand locations can change; the live official list is linked instead of copied as permanent facts.",
  },
];

export const evidenceRegistry: EvidenceRecord[] = [
  { id: "e-ad-001", sourceId: "th-ad-sote-2026", page: "2", section: "Välityslaite ja ohjelmisto", claim: "The AD Kuljettaja program is installed on a Samsung Android device protected by Knox; the guide says keeping the app in the foreground and avoiding the key lock is important so offers arrive.", topic: "AD_DEVICE", confidence: "high" },
  { id: "e-ad-002", sourceId: "th-ad-sote-2026", page: "3", section: "Sovellukseen kirjautuminen", claim: "The public SOTE guide describes SMS login: open the app, choose SMS, enter the received code, and press the login-by-code button.", topic: "AD_LOGIN", confidence: "high" },
  { id: "e-ad-003", sourceId: "th-ad-sote-2026", page: "6", section: "Työvuoron aloitus", claim: "A driver starts a shift by choosing the company and vehicle, setting the shift duration, and saving the shift.", topic: "AD_SHIFT", confidence: "high" },
  { id: "e-ad-004", sourceId: "th-ad-sote-2026", page: "7", section: "Varattuna olo", claim: "When marked as reserved, the driver does not receive driving offers; the guide tells the driver to return to the driving state when available.", topic: "AD_STATUS", confidence: "high" },
  { id: "e-ad-005", sourceId: "th-ad-sote-2026", page: "8", section: "Ajotarjous", claim: "The offer view shows pickup time, pickup and destination addresses, an estimated price, special requirements, and the number of customers and stages.", topic: "AD_OFFER", confidence: "high" },
  { id: "e-ad-006", sourceId: "th-ad-sote-2026", page: "9–12", section: "Matkan aloittaminen ja vaiheet", claim: "The public guide describes the trip-state sequence: open the trip, start it, mark arrival, mark pickup ready, handle no-show when applicable, mark arrival at destination, and mark the destination complete.", topic: "AD_TRIP_STATES", confidence: "high" },
  { id: "e-ad-007", sourceId: "th-ad-sote-2026", page: "13", section: "Avoimet-lista", claim: "The open list contains orders for which no vehicle has been found and can be sorted by time or distance.", topic: "AD_OPEN_LIST", confidence: "high" },
  { id: "e-ad-008", sourceId: "th-ad-sote-2026", page: "15–16", section: "Ruudut", claim: "The new Ruudut view has vehicle-type filters and shows queue-related values for 30, 60, and 120 minute windows as described in the guide.", topic: "AD_RUUDUT", confidence: "high" },
  { id: "e-ad-009", sourceId: "th-ad-sote-2026", page: "17", section: "Matkahistoria", claim: "Trip history can be filtered by date, and the trip details include a UUID that can be used when a billing correction request is needed.", topic: "AD_HISTORY", confidence: "high" },
  { id: "e-ad-010", sourceId: "th-ad-sote-2026", page: "19", section: "Ongelmia?", claim: "For a server or GPS connection error, the guide says to use the red connection icon and the refresh-connections action; notification permissions may also be required.", topic: "AD_TROUBLESHOOTING", confidence: "high" },
  { id: "e-ad-011", sourceId: "th-ad-sote-2026", page: "20", section: "Ongelmia?", claim: "For a slow or unresponsive device, the guide describes ending the shift, logging out, closing the app, and powering the device off.", topic: "AD_RESTART", confidence: "high" },
  { id: "e-kela-001", sourceId: "th-ad-kela-2024", page: "2", section: "Kirjautuminen tekstiviestillä", claim: "The historical Kela guide describes SMS login using a phone number and a four-digit SMS code.", topic: "KELA_AD_LOGIN", confidence: "high" },
  { id: "e-kela-002", sourceId: "th-ad-kela-2024", page: "3–4", section: "Pikaohje", claim: "The historical Kela guide lists driver, vehicle, messages, offers, future trips, trip history, open list, and Ruudut areas in the application.", topic: "KELA_AD_MENU", confidence: "high" },
  { id: "e-kela-003", sourceId: "th-ad-kela-2024", page: "5–7", section: "Työvuoron aloittaminen", claim: "The historical Kela guide says offers are received during an active saved shift and distinguishes Ajossa from Varattuna.", topic: "KELA_AD_SHIFT", confidence: "high" },
  { id: "e-kela-004", sourceId: "th-ad-kela-2024", page: "8–10", section: "Tarjouksen hyväksyminen tai hylkääminen / Matkan aloittaminen", claim: "The historical Kela guide lists offer details and the trip-state controls for start, arrival, pickup ready, no-show, and completion.", topic: "KELA_AD_TRIP", confidence: "high" },
  { id: "e-kela-005", sourceId: "th-ad-kela-2024", page: "12", section: "Matkahistoria", claim: "The historical Kela guide says the meter data is joined to application data using the order identifier, so the correct order identifier should be used in the meter.", topic: "KELA_METER_LINK", confidence: "high" },
  { id: "e-kela-006", sourceId: "th-ad-kela-2024", page: "14–15", section: "Yhteydet ja asetukset / Ongelmia?", claim: "The historical Kela guide describes refreshing server/GPS connections and checking notification and location permissions.", topic: "KELA_AD_TROUBLESHOOTING", confidence: "high" },
  { id: "e-kela-007", sourceId: "th-ad-kela-2024", page: "16–17", section: "Luokseajokorvaus", claim: "The historical Kela guide contains a historical description and examples of approach compensation, including a stated maximum in that document.", topic: "KELA_COMPENSATION", confidence: "high" },
  { id: "e-quality-001", sourceId: "th-quality-commitment", page: "1", section: "Sanktiot", claim: "The quality commitment lists possible consequences for breaches, including a notice, attribute removal, guidance discussion, training or test requirements, a dispatch ban, or a driving ban.", topic: "QUALITY_CONTROLS", confidence: "high" },
  { id: "e-quality-002", sourceId: "th-quality-commitment", page: "2", section: "Kuljettajan sitoumukset", claim: "The driver commitment includes following the current Taksi Helsinki price list or agreed maximum price, keeping the driver card visible, keeping the vehicle and workwear clean, following clothing guidance, and not smoking in the taxi.", topic: "QUALITY_APPEARANCE", confidence: "high" },
  { id: "e-quality-003", sourceId: "th-quality-commitment", page: "2–3", section: "Tilausvälitysjärjestelmä", claim: "The driver commitment says the accepted order should be read in full promptly and the service centre should be contacted if the order information is missing.", topic: "QUALITY_ORDER", confidence: "high" },
  { id: "e-quality-004", sourceId: "th-quality-commitment", page: "3", section: "Reitti ja lisähinta", claim: "The commitment says the driver should use the most economical or appropriate route unless the customer requests another route and should proactively compensate an extra charge caused by the driver's own route error.", topic: "QUALITY_ROUTE", confidence: "high" },
  { id: "e-quality-005", sourceId: "th-quality-commitment", page: "3–4", section: "Maksaminen ja kuitti", claim: "The commitment includes accepting common payment methods and offering the customer a receipt, including for a cash payment.", topic: "QUALITY_PAYMENT", confidence: "high" },
  { id: "e-quality-006", sourceId: "th-quality-commitment", page: "4–5", section: "Yksityisyys ja asiakaspalvelu", claim: "The commitment requires confidentiality, limits customer calls to matters directly connected to the order, and says the driver should not use a phone for unrelated matters while a customer is in the vehicle.", topic: "QUALITY_PRIVACY", confidence: "high" },
  { id: "e-quality-007", sourceId: "th-quality-commitment", page: "5–6", section: "Asiakaspalvelu", claim: "The commitment says the driver should offer help when needed, handle lost property according to the law, avoid sensitive conversation starters, give the customer travel peace, and not block the front seat without a valid reason.", topic: "QUALITY_CUSTOMER_SERVICE", confidence: "high" },
  { id: "e-service-001", sourceId: "th-services-drivers", page: "web page", section: "Services for operators", claim: "The public services page links to Cabman MDT meter ordering information, dispatch-device ordering information, vehicle and Kela-connection services, and a contract taxi stand page.", topic: "DRIVER_SERVICES", confidence: "high" },
  { id: "e-app-001", sourceId: "th-app-guide", page: "web page", section: "Ordering a taxi", claim: "The public customer app guide explains that the app can show a fixed price when a destination is entered, while a ride ordered without a destination is priced by the meter according to the guide.", topic: "PUBLIC_PRICING", confidence: "high" },
  { id: "e-materials-001", sourceId: "th-materials", page: "login page", section: "Materiaalisalkku", claim: "The official Materiaalisalkku entry point redirects to an Extranet login; the requested private driver materials were not available for public extraction.", topic: "RESTRICTED_MATERIAL", confidence: "high" },
  { id: "e-notices-001", sourceId: "th-driver-notices", page: "login page", section: "Kuljettajatiedotteet", claim: "The official driver-notice entry point redirects to an Extranet login; no current notice is presented as a fact without public access to the notice itself.", topic: "RESTRICTED_NOTICES", confidence: "high" },
  { id: "e-kela-historical-001", sourceId: "th-kela-service-description-2022", page: "5–9", section: "Historical service description", claim: "The 2021–2022 service description discusses regional dispatch, electronic direct-compensation data, TAKSO, and special vehicle needs; it is historical and is not a current 2026 procedure.", topic: "KELA_HISTORICAL", confidence: "high" },
  { id: "e-kela-current-001", sourceId: "kela-transport", page: "web page", section: "Additional information for the person booking a Kela taxi", claim: "Kela says the dispatch centre receives the authorised vehicle type and can add continuing information about special assistance or assistive devices to the customer data.", topic: "KELA_SPECIAL_NEEDS", confidence: "high" },
  { id: "e-th-kela-001", sourceId: "th-kela", page: "web page", section: "Good to know about Kela transports", claim: "Taksi Helsinki says drivers who drive Kela rides have completed the taxi traffic special groups driver training and the Taksi Helsinki Kela driver training.", topic: "KELA_DRIVER_TRAINING", confidence: "high" },
  { id: "e-kela-th-001", sourceId: "th-kela-autot", page: "web page", section: "Käynnissä oleva sopimuskausi 31.12.2026 asti", claim: "The current Taksi Helsinki Kela page says it dispatches Kela-reimbursed journeys in Uusimaa, Kanta-Häme, Varsinais-Suomi, Pirkanmaa, Satakunta, Keski-Suomi, Pohjois-Savo and Lapland through 31.12.2026.", topic: "KELA_CURRENT_REGIONS", confidence: "high" },
  { id: "e-kela-th-002", sourceId: "th-kela-autot", page: "web page", section: "Yleistä Taksi Helsingin Kela-välityksestä", claim: "The current operator page says Taksi Helsinki uses Ahola Digital for dispatch and can connect Kela dispatch to an existing terminal or provide a phone-style terminal; it lists Cabman MDT, Semel M2, Mitax 300 and Mitax 400 as certified meter models.", topic: "KELA_DISPATCH_AND_METERS", confidence: "high" },
  { id: "e-kela-future-001", sourceId: "th-kela-2027", page: "web page", section: "Sopimuskausi ja aikataulu", claim: "The future page describes a Kela contract period from 1.1.2027 to 31.12.2030 in Uusimaa, Kanta-Häme, Varsinais-Suomi, South Karelia and Lapland, with dispatch starting 1.1.2027.", topic: "KELA_2027_CONTRACT", effectiveDate: "2027-01-01", confidence: "high" },
  { id: "e-kela-future-002", sourceId: "th-kela-2027", page: "web page", section: "Laitevaatimukset", claim: "For the future contract period, the page lists accepted dispatch devices as Samsung Xcover 5, Xcover 7, Tab Active 3 and Tab Active 5, and accepted meters as Semel M2, Mitax 300, Mitax 400, Mitax 500 and Cabman.", topic: "KELA_2027_EQUIPMENT", effectiveDate: "2027-01-01", confidence: "high" },
  { id: "e-kela-future-003", sourceId: "th-kela-2027", page: "web page", section: "Kuljettajavaatimukset ja koulutus", claim: "For the future contract period, the page lists a valid driving licence, valid taxi driver professional licence, sufficient domestic-language skills, completed special-groups driver training and completed Taksi Helsinki Kela online training among driver requirements; the updated Kela training is scheduled to open in November 2026.", topic: "KELA_2027_DRIVER_REQUIREMENTS", effectiveDate: "2027-01-01", confidence: "high" },
  { id: "e-kela-future-004", sourceId: "th-kela-2027", page: "web page", section: "Usein kysytyt kysymykset", claim: "The future page says the toivetaksi practice continues for the new contract period and distinguishes it from Kela-granted familiar-driver rights.", topic: "KELA_REQUESTED_TAXI", effectiveDate: "2027-01-01", confidence: "high" },
];

export const knowledgeModules: KnowledgeModule[] = [
  { id: "driver-path", number: "01", title: "Taksi Helsinki Driver Path", description: "الطريق المنشور من التقييم والتدريب إلى التعلم العملي، مع فصل سياسة الشركة عن رخصة Traficom.", status: "official_current", sourceIds: ["th-training", "traficom-licence"], lessonIds: ["kb-driver-path-001"] },
  { id: "customer-service", number: "02", title: "Customer Service", description: "التزام الجودة المنشور: الخصوصية، الهدوء، المساعدة، والاحتراف في التعامل.", status: "official_current", sourceIds: ["th-quality-commitment"], lessonIds: ["kb-quality-001", "kb-quality-002"] },
  { id: "ad-driver", number: "03", title: "AD Kuljettaja", description: "وحدة تشغيلية مبنية على دليل AD Kuljettaja SOTE العام بتاريخ 02.02.2026.", status: "official_current", sourceIds: ["th-ad-sote-2026"], lessonIds: ["kb-ad-001", "kb-ad-002", "kb-ad-003", "kb-ad-004"] },
  { id: "autocab", number: "04", title: "Autocab", description: "لا تُعرض تعليمات Autocab الداخلية دون دليل رسمي عام قابل للقراءة.", status: "access_restricted", sourceIds: ["th-materials"], lessonIds: ["kb-autocab-001"] },
  { id: "cabman", number: "05", title: "Cabman / Taximeter", description: "تسجيل ما يؤكده المصدر العام فقط، مع إبقاء خطوات Cabman التفصيلية غير موثقة.", status: "official_current", sourceIds: ["th-services-drivers", "th-quality-commitment"], lessonIds: ["kb-meter-001"] },
  { id: "other-meters", number: "06", title: "Other Meter Systems", description: "Mitax 300 وMitax 400 وSemel M2 مسجلة، لكن استخراج النص لم يثبت أزرارًا أو خطوات تشغيلية.", status: "official_current", sourceIds: ["th-mitax-300", "th-mitax-400", "th-semel-m2"], lessonIds: ["kb-meter-002"] },
  { id: "pricing", number: "07", title: "Pricing", description: "قواعد عامة موثقة للأجرة والشفافية، مع رابط حي بدل نسخ أسعار قابلة للتغير.", status: "official_current", sourceIds: ["th-pricing", "th-quality-commitment", "th-app-guide"], lessonIds: ["kb-pricing-001"] },
  { id: "local-knowledge", number: "08", title: "Helsinki Local Knowledge", description: "المعرفة المحلية كما يذكرها التدريب، دون اختلاق قائمة أماكن أو مسارات تشغيلية.", status: "official_current", sourceIds: ["th-training", "th-front"], lessonIds: ["kb-local-001"] },
  { id: "areas-opening", number: "09", title: "Areas and Opening Times", description: "القوائم الزمنية التفصيلية غير موجودة في المصادر العامة المفحوصة.", status: "not_verified", sourceIds: ["th-materials", "th-driver-notices"], lessonIds: ["kb-areas-001"] },
  { id: "taxi-stands", number: "10", title: "Taxi Stands", description: "رابط قائمة المواقف الرسمية محفوظ، لكن المواقع تتغير ولا تُنسخ كحقائق ثابتة.", status: "official_current", sourceIds: ["th-taxi-stands"], lessonIds: ["kb-stands-001"] },
  { id: "airport", number: "11", title: "Airport", description: "صفحة المطار الرسمية مكتشفة، لكن تعليمات انتظار السائق الخاصة لا تُعرض دون دليل عام واضح.", status: "not_verified", sourceIds: ["th-airport"], lessonIds: ["kb-airport-001"] },
  { id: "ports", number: "12", title: "Ports", description: "صفحة الموانئ الرسمية مكتشفة، لكن إجراءات السائق التفصيلية غير مثبتة في هذا البناء.", status: "not_verified", sourceIds: ["th-ports"], lessonIds: ["kb-ports-001"] },
  { id: "kela", number: "13", title: "Kela", description: "فصل بين الإرشاد الحالي، تشغيل Kela المنشور، عقد 2027 المستقبلي، ودليل التطبيق التاريخي.", status: "official_current", sourceIds: ["kela-transport", "th-kela", "th-kela-autot", "th-ad-kela-2024", "th-kela-2027"], lessonIds: ["kb-kela-001", "kb-kela-002", "kb-kela-003", "kb-kela-004"] },
  { id: "special-transport", number: "14", title: "Special Transport", description: "ما تؤكده المصادر عن احتياجات المركبة والمساعدة وتدريب السائق، دون تحويل عقد قديم إلى قاعدة حالية.", status: "official_current", sourceIds: ["kela-transport", "th-kela", "th-kela-autot", "th-kela-service-description-2022"], lessonIds: ["kb-special-001"] },
  { id: "quality", number: "15", title: "Driver Quality Requirements", description: "التزامات الجودة المنشورة في وثيقة Taksi Helsinki الرسمية.", status: "official_current", sourceIds: ["th-quality-commitment"], lessonIds: ["kb-quality-001", "kb-quality-002"] },
  { id: "clothing", number: "16", title: "Clothing and Professional Appearance", description: "تنظيف السيارة والزي وبطاقة السائق كما وردت في الالتزام الرسمي.", status: "official_current", sourceIds: ["th-quality-commitment"], lessonIds: ["kb-quality-002"] },
  { id: "privacy", number: "17", title: "Privacy", description: "السرية، الهاتف، واتصالات العميل كما وردت في وثيقة الجودة.", status: "official_current", sourceIds: ["th-quality-commitment", "th-kela-service-description-2022"], lessonIds: ["kb-quality-003"] },
  { id: "special-services", number: "18", title: "Special Services", description: "الخدمات العامة المرتبطة بـ Cabman MDT، جهاز الإرسال، Kela والمواقف التعاقدية.", status: "official_current", sourceIds: ["th-services-drivers"], lessonIds: ["kb-services-001"] },
  { id: "scenarios", number: "19", title: "Practical Driver Scenarios", description: "حالات تطبيقية مشتقة مباشرة من الأدلة، لا خطوات مخترعة.", status: "official_current", sourceIds: ["th-ad-sote-2026", "th-quality-commitment"], lessonIds: ["kb-ad-003", "kb-quality-003"] },
  { id: "exam", number: "20", title: "Exam Preparation", description: "أسئلة تدريبية أصلية مرتبطة بالأدلة، وليست أسئلة الامتحان الحقيقي.", status: "official_current", sourceIds: ["traficom-licence", "traficom-reform"], lessonIds: ["kb-exam-001"] },
];

export const knowledgeLessons: KnowledgeLesson[] = [
  {
    id: "kb-driver-path-001",
    moduleId: "driver-path",
    title: "فصل مسار الشركة عن رخصة Traficom",
    summary: "المسار التعليمي يميز بين التدريب الذي تنشره Taksi Helsinki وبين رخصة قيادة التاكسي واختبارها لدى Traficom.",
    whatYouNeedToKnow: ["صفحة Taksi Helsinki تشرح مسار تدريب الشركة ومراحلها المنشورة.", "Traficom هي مصدر شروط رخصة قيادة التاكسي والاختبار الحكومي.", "لا تستخدم نجاح اختبار الشركة كدليل على إصدار الرخصة الحكومية."],
    officialProcedure: ["راجع صفحة التدريب الرسمية لمتطلبات Taksi Helsinki الحالية.", "راجع صفحة Traficom قبل التقديم أو حجز الاختبار.", "افتح المصدر عند تغير التاريخ أو الشروط؛ لا تعتمد على ملخص ثابت وحده."],
    terminology: ["Kuljettajakoulutus", "Kuljettajankoe", "Taksinkuljettajan ajolupa", "Ajovarma"],
    commonMistake: "الخلط بين Kuljettajankoe الخاص بالشركة واختبار Traficom.",
    sourceIds: ["th-training", "traficom-licence"],
    evidenceIds: [],
    lastVerified: verifiedOn,
    status: "official_current",
  },
  {
    id: "kb-quality-001",
    moduleId: "customer-service",
    title: "التزام الجودة: ماذا يعني السلوك المهني؟",
    summary: "وثيقة Kuljettajan laatusitoumus تحول الجودة إلى التزامات قابلة للمراجعة، لا إلى نصائح عامة.",
    whatYouNeedToKnow: ["الوثيقة تذكر عواقب محتملة لمخالفة الالتزامات، ومنها التدريب أو الاختبار أو منع الإرسال أو منع القيادة.", "السائق يتعهد بالتصرف باحترام واتباع القانون وحماية خصوصية العميل.", "الوثيقة تعطي Taksi Helsinki وموظفي الجودة صلاحية المتابعة والتحقق."],
    officialProcedure: ["اقرأ الطلب أو المعلومة كاملة قبل تنفيذ الرحلة.", "عند مشكلة في الطلب، استخدم قناة الخدمة الضرورية بدل ترك الرحلة بلا معالجة.", "التزم بالتعليمات السارية التي تصدرها الشركة عبر قنواتها الرسمية."],
    terminology: ["Laatusitoumus", "Tilausvälitys", "Ajokielto", "Tilausvälityskielto"],
    commonMistake: "اعتبار قواعد الجودة اقتراحات اختيارية أو اعتبارها بديلًا عن التعليمات الأحدث.",
    scenario: { title: "معلومة الطلب ناقصة", happened: "قبل الوصول لا تظهر للسائق معلومات الطلب المقبول كاملة.", why: "وثيقة الجودة تقول إن معلومات الطلب يجب قراءتها، وإن مركز الخدمة يُتصل به فورًا عند فقدانها.", officialGuidance: "لا نخترع مسار إصلاح داخل النظام؛ الدليل يثبت الاتصال بمركز الخدمة عند غياب البيانات.", nextStep: "اتبع قناة مركز الخدمة الرسمية، ثم وثّق المشكلة وفق الإجراء الداخلي المتاح لك." },
    sourceIds: ["th-quality-commitment"],
    evidenceIds: ["e-quality-001", "e-quality-003"],
    lastVerified: verifiedOn,
    status: "official_current",
  },
  {
    id: "kb-quality-002",
    moduleId: "quality",
    title: "المظهر، بطاقة السائق، والنظافة",
    summary: "تضع وثيقة Taksi Helsinki التزامات محددة للبطاقة، السيارة، اللباس، وعدم التدخين.",
    whatYouNeedToKnow: ["بطاقة السائق يجب أن تكون ظاهرة بحيث يستطيع العميل رؤيتها بسهولة.", "السيارة والزي يجب أن يكونا نظيفين ومرتبين في بداية الوردية.", "الوثيقة تتضمن عدم التدخين، بما في ذلك السجائر الإلكترونية والمنتجات المشابهة، داخل التاكسي."],
    officialProcedure: ["افحص النظافة والبطاقة والزي قبل بداية الوردية.", "راجع أحدث تعليمات اللباس من Taksi Helsinki؛ لا نضع تفاصيل غير منشورة هنا.", "افتح وثيقة الالتزام إذا احتجت النص الفنلندي الكامل."],
    terminology: ["Kuljettajakortti", "Pukeutumisohje", "Työvuoro"],
    commonMistake: "نقل تفاصيل زي قديم أو اعتبار صورة عامة دليلًا على مواصفات اللباس الحالية.",
    sourceIds: ["th-quality-commitment"],
    evidenceIds: ["e-quality-002"],
    lastVerified: verifiedOn,
    status: "official_current",
  },
  {
    id: "kb-quality-003",
    moduleId: "privacy",
    title: "الخصوصية وراحة العميل",
    summary: "الالتزام الرسمي يربط السرية بسلوك عملي أثناء الرحلة وبعدها.",
    whatYouNeedToKnow: ["الوثيقة تنص على السرية لحماية خصوصية العميل.", "لا تستخدم الهاتف لأمور لا تتعلق بالرحلة أثناء وجود العميل.", "اتصل بالعميل فقط لأمور مرتبطة مباشرة بالطلب، مثل صعوبة العثور على العنوان أو التأخير."],
    officialProcedure: ["اجعل الاتصال مرتبطًا بالطلب الحالي فقط.", "اترك للعميل راحة الرحلة إذا لم يبدأ الحوار.", "تعامل مع المفقودات وفق القانون والقنوات الرسمية؛ لا نخترع قناة تسليم داخلية."],
    terminology: ["Vaitiolovelvollisuus", "Asiakas", "Tilausnumero"],
    commonMistake: "استخدام رقم العميل لأمر شخصي أو استمرار التواصل بعد الرحلة دون سبب مرتبط بالطلب.",
    scenario: { title: "هاتف العميل بعد الرحلة", happened: "يريد السائق الاتصال بالعميل لأمر لا يتعلق بالطلب.", why: "وثيقة الجودة تقصر الاتصال على المسائل المرتبطة مباشرة بالطلب وتحمي خصوصية العميل.", officialGuidance: "لا يوجد في الدليل تصريح لاتصال شخصي؛ القاعدة المنشورة هي تقييد الاتصال بالطلب.", nextStep: "لا تستخدم بيانات الاتصال خارج الغرض المرتبط بالرحلة، واستشر القناة الرسمية عند وجود حالة استثنائية." },
    sourceIds: ["th-quality-commitment"],
    evidenceIds: ["e-quality-006", "e-quality-007"],
    lastVerified: verifiedOn,
    status: "official_current",
  },
  {
    id: "kb-ad-001",
    moduleId: "ad-driver",
    title: "الجهاز وتسجيل الدخول في AD Kuljettaja",
    summary: "دليل 02.02.2026 يشرح الجهاز المخصص، SMS login، ولماذا يجب إبقاء التطبيق في المقدمة.",
    whatYouNeedToKnow: ["الدليل الحالي يصف جهاز Samsung Android مثبتًا ومجهزًا للعمل.", "اختيار SMS ثم إدخال الرمز والضغط على تسجيل الدخول هي الخطوات المنشورة في صفحة الدخول.", "إبقاء التطبيق في الخلفية أو استخدام قفل المفاتيح قد يمنع وصول عروض الرحلات وفق الدليل."],
    officialProcedure: ["افتح AD Kuljettaja واختر SMS.", "أدخل الرمز الذي يصل إلى الجهاز ثم اختر تسجيل الدخول بالرمز.", "أبقِ البرنامج في المقدمة وتجنب قفل المفاتيح أثناء الوردية."],
    terminology: ["AD Kuljettaja", "SMS", "Kirjaudu ulos", "Knox"],
    commonMistake: "تقديم شرح عام عن App Store أو Google Play؛ الدليل الحالي الذي قُرئ يصف جهاز Samsung مُسلّمًا ومثبتًا، ولا يثبت تثبيتًا حرًا من متجر.",
    sourceIds: ["th-ad-sote-2026"],
    evidenceIds: ["e-ad-001", "e-ad-002"],
    lastVerified: verifiedOn,
    status: "official_current",
  },
  {
    id: "kb-ad-002",
    moduleId: "ad-driver",
    title: "بداية الوردية وحالة Varattuna",
    summary: "قبل استلام العروض يجب اختيار الشركة والسيارة وحفظ وقت الوردية؛ حالة Varattuna تمنع عروض الرحلات.",
    whatYouNeedToKnow: ["يختار السائق الشركة والسيارة ثم يحدد بداية ونهاية الوردية ويحفظها.", "يمكن تعديل أوقات الوردية من قائمة Kuljettaja.", "عند Varattuna لا تصل عروض القيادة، ويجب العودة إلى Olet ajossa عند التفرغ."],
    officialProcedure: ["افتح قائمة Kuljettaja.", "اختر الشركة والسيارة واضبط مدة الوردية.", "احفظ الوردية.", "استخدم مفتاح Olet ajossa / Varattuna بحسب حالتك الفعلية."],
    terminology: ["Työvuoro", "Olet ajossa", "Varattuna", "Kuljettaja"],
    commonMistake: "نسيان حفظ الوردية أو البقاء في Varattuna ثم افتراض أن عدم وصول العروض عطل في النظام.",
    sourceIds: ["th-ad-sote-2026"],
    evidenceIds: ["e-ad-003", "e-ad-004"],
    lastVerified: verifiedOn,
    status: "official_current",
  },
  {
    id: "kb-ad-003",
    moduleId: "ad-driver",
    title: "من العرض إلى إتمام الرحلة",
    summary: "دليل AD الحالي يثبت تسلسل الحالات والأزرار الرئيسية دون إعادة رسم واجهة رسمية.",
    whatYouNeedToKnow: ["العرض يضم وقت ومكان الاستلام والوجهة وتقدير الأجرة والمتطلبات الخاصة.", "تسلسل الرحلة يتضمن البدء، الوصول للمكان، جاهزية الاستلام، ثم الوصول للوجهة وإنهائها.", "كل تأكيدات المراحل تظهر لمشغلي الإرسال، وبعضها يرسل إشعارًا للعميل وفق الدليل."],
    officialProcedure: ["افتح الرحلة من قائمة Matkat.", "اضغط ALOITA MATKA.", "عند الوصول اضغط SAAVUIN PAIKALLE ثم عند ركوب العميل NOUTO VALMIS.", "عند الوجهة اضغط SAAVUIN PAIKALLE ثم MÄÄRÄNPÄÄ VALMIS.", "إذا لم يحضر العميل استخدم حالة ASIAKAS EI SAAPUNUT عندما تنطبق."],
    terminology: ["Ajotarjous", "Aloita matka", "Saavuin paikalle", "Nouto valmis", "Määränpää valmis"],
    commonMistake: "اختصار مراحل الرحلة أو اختيار حالة لا تطابق ما حدث فعليًا.",
    scenario: { title: "العميل لم يحضر", happened: "وصل السائق إلى مكان الاستلام ولم يظهر العميل.", why: "الدليل الحالي يذكر حالة ASIAKAS EI SAAPUNUT كمرحلة مخصصة لهذه الحالة.", officialGuidance: "نثبت وجود الحالة فقط؛ لا نضيف مدة انتظار أو إجراء تعويض غير وارد في الدليل الحالي.", nextStep: "استخدم الحالة المنشورة عندما تنطبق واتبع أي تعليمات حالية تظهر في الطلب أو تصل عبر القنوات الرسمية." },
    sourceIds: ["th-ad-sote-2026"],
    evidenceIds: ["e-ad-005", "e-ad-006"],
    lastVerified: verifiedOn,
    status: "official_current",
  },
  {
    id: "kb-ad-004",
    moduleId: "ad-driver",
    title: "Avoimet وRuudut وسجل الرحلات",
    summary: "الدليل يشرح قائمة الطلبات المفتوحة، عرض Ruudut، تاريخ الرحلات، ومؤشر UUID.",
    whatYouNeedToKnow: ["Avoimet تعرض الطلبات التي لم تجد سيارة، ويمكن ترتيبها بالوقت أو المسافة.", "Ruudut تعرض مرشحات مرتبطة بنوع السيارة وقيمًا زمنية للطلبات في نوافذ 30 و60 و120 دقيقة كما ورد في الدليل.", "Matkahistoria تسمح بالبحث في رحلات يوم محدد، وتعرض UUID عند الحاجة إلى طلب تصحيح الفوترة."],
    officialProcedure: ["افتح Avoimet واختر ترتيب الوقت أو المسافة حسب الحاجة.", "استخدم Ruudut لعرض الروابط والمرشحات المتاحة لجهازك.", "افتح Matkahistoria واختر التاريخ ثم LASKU أو TIEDOT."],
    terminology: ["Avoimet", "Ruudut", "Matkahistoria", "UUID"],
    commonMistake: "اعتبار أرقام 30/60/120 أسعارًا أو مواعيد وصول؛ الدليل يشرحها كقيم في عرض Ruudut.",
    sourceIds: ["th-ad-sote-2026"],
    evidenceIds: ["e-ad-007", "e-ad-008", "e-ad-009"],
    lastVerified: verifiedOn,
    status: "official_current",
  },
  {
    id: "kb-autocab-001",
    moduleId: "autocab",
    title: "Autocab: حالة المصدر قبل إضافة أي إجراء",
    summary: "NOT_VERIFIED — لم نجد دليل Autocab عامًا قابلًا للقراءة في المصدر المفتوح؛ صفحة Materiaalisalkku تحيل إلى Extranet.",
    whatYouNeedToKnow: ["المصدر الرسمي لمواد السائق موجود خلف تسجيل الدخول عند التحقق.", "لم نستخدم دليلًا مسرّبًا أو صفحة ثانوية لإثبات أزرار أو خطوات Autocab.", "AI_ASSISTANT ≠ AUTHORITATIVE_SOURCE: لا يجوز تحويل إجابة مساعد آلي إلى سياسة تشغيلية."],
    officialProcedure: ["NOT_VERIFIED — لا توجد خطوات تشغيلية عامة نثبتها هنا.", "افتح المصدر الرسمي بعد حصولك على وصول مخول، ثم سجّل الإصدار والصفحات قبل إدخاله إلى قاعدة الأدلة."],
    terminology: ["Autocab", "ACCESS_RESTRICTED", "NOT_VERIFIED"],
    commonMistake: "اختراع مسار قبول رحلة أو ربط Autocab بـ Cabman من الذاكرة.",
    sourceIds: ["th-materials"],
    evidenceIds: ["e-materials-001"],
    lastVerified: verifiedOn,
    status: "access_restricted",
  },
  {
    id: "kb-meter-001",
    moduleId: "cabman",
    title: "Cabman: ما الذي يثبته المصدر العام؟",
    summary: "الصفحة الرسمية تذكر أن Cabman MDT هو أحد أنظمة العداد التي توفر Taksi Helsinki لها طلبًا وتعليمات؛ لا نعرض أزرارًا غير مقروءة.",
    whatYouNeedToKnow: ["صفحة خدمات المشغلين تربط إلى طلب Cabman MDT وتعليماته.", "وثيقة الجودة تتوقع معرفة السائق بالخصائص الشائعة للعداد، مثل المدفوعات الإضافية أو الدفع المقسم.", "لم يتم استخدام رابط الطلب أو نموذج تجاري لإثبات تسلسل أزرار Cabman."],
    officialProcedure: ["افتح التعليمات الحالية من صفحة خدمات المشغلين أو Materiaalisalkku عند توفر وصول رسمي.", "احتفظ برقم إصدار الدليل قبل تحويله إلى درس.", "لا تستخدم هذا الدرس كبديل عن دليل Cabman الخاص بالمركبة."],
    terminology: ["Cabman MDT", "Taksamittari", "Lisämaksu", "Jaettu maksu"],
    commonMistake: "تعميم خطوة من Mitax أو Semel على Cabman.",
    sourceIds: ["th-services-drivers", "th-quality-commitment"],
    evidenceIds: ["e-service-001", "e-quality-005"],
    lastVerified: verifiedOn,
    status: "official_current",
  },
  {
    id: "kb-meter-002",
    moduleId: "other-meters",
    title: "Mitax 300 وMitax 400 وSemel M2",
    summary: "هذه الأدلة مسجلة في السجل الرسمي، لكن استخراج النص العام أظهر العنوان وعدد الصفحات فقط؛ لذلك لا نملأ خطوات التشغيل من التخمين.",
    whatYouNeedToKnow: ["Mitax 300 وMitax 400 وSemel M2 لها ملفات PDF رسمية مرتبطة بالموقع.", "الملفات الثلاثة لم تعطِ نصًا قابلاً للتحقق عن الأزرار عبر الاستخراج العام المستخدم.", "الدرس الحالي يشرح حدود الدليل، لا طريقة تشغيل العداد."],
    officialProcedure: ["NOT_VERIFIED — افتح ملف العداد الرسمي الحالي من سجل المصادر.", "تحقق من رقم الإصدار والطراز قبل استخدام أي خطوة.", "لا تخلط بين دليل Kela التاريخي وتعليمات العداد الحالية."],
    terminology: ["Mitax 300", "Mitax 400", "Semel M2"],
    commonMistake: "إسناد خطوات Cabman إلى Mitax أو افتراض أن جميع العدادات تعمل بنفس الواجهة.",
    sourceIds: ["th-mitax-300", "th-mitax-400", "th-semel-m2"],
    evidenceIds: [],
    lastVerified: verifiedOn,
    status: "official_current",
  },
  {
    id: "kb-pricing-001",
    moduleId: "pricing",
    title: "الأجرة: رابط حي بدل رقم قابل للتقادم",
    summary: "نربط إلى صفحة السعر الحالية، ونستخدم وثيقة الجودة لتأكيد الالتزام بالسعر المعتمد، دون نسخ أسعار قد تتغير.",
    whatYouNeedToKnow: ["وثيقة الجودة تلزم السائق باتباع قائمة Taksi Helsinki أو السعر الأقصى أو السعر المتفق عليه مع العميل.", "دليل تطبيق العميل يصف عرض سعر ثابت عند إدخال الوجهة، وتسعيرًا بالعداد عند عدم إدخالها وفق الصفحة العامة.", "لا تحفظ المنصة جدول أسعار ثابتًا؛ افتح المصدر الرسمي قبل اعتماد رقم."],
    officialProcedure: ["افتح صفحة Taksin hinta الرسمية للحصول على السعر الحالي.", "اتبع السعر الظاهر في الطلب أو الاتفاق المسموح به.", "لا تحول مثالًا قديمًا إلى سعر حالي."],
    terminology: ["Hinnasto", "Kiinteä hinta", "Taksamittari", "Maksutapa"],
    commonMistake: "عرض سعر محفوظ في التطبيق على أنه السعر الحالي.",
    sourceIds: ["th-pricing", "th-quality-commitment", "th-app-guide"],
    evidenceIds: ["e-quality-002", "e-app-001"],
    lastVerified: verifiedOn,
    status: "official_current",
  },
  {
    id: "kb-local-001",
    moduleId: "local-knowledge",
    title: "المعرفة المحلية بدون خريطة مخترعة",
    summary: "تثبت صفحة التدريب أن المعرفة المحلية جزء من الإعداد، لكن المصدر المفتوح المفحوص لا يقدم قائمة تشغيلية كاملة بالأماكن والمسارات.",
    whatYouNeedToKnow: ["التدريب الإلكتروني يذكر المعرفة المحلية لمنطقة pääkaupunkiseutu.", "التدريب العملي يذكر التعرف على أهم الأماكن.", "لا نضع أسماء مواقف أو بوابات أو مسارات من الذاكرة؛ نربط بالقائمة الحية الرسمية عند وجودها."],
    officialProcedure: ["استخدم مصادر الشركة الحالية لتحديث الأماكن.", "تحقق من عنوان الاستلام والوجهة من الطلب نفسه.", "عند عدم توفر تعليمات عامة، صنف المعلومة NOT_VERIFIED."],
    terminology: ["Pääkaupunkiseutu", "Nouto-osoite", "Määränpää"],
    commonMistake: "استخدام دليل سياحي أو منشور قديم لإثبات مكان تشغيل أو وقت فتح.",
    sourceIds: ["th-training", "th-front"],
    evidenceIds: [],
    lastVerified: verifiedOn,
    status: "official_current",
  },
  {
    id: "kb-areas-001",
    moduleId: "areas-opening",
    title: "المناطق وأوقات الفتح — NOT_VERIFIED",
    summary: "لم نعثر على جدول عام موثق يثبت كل منطقة تشغيل ووقت فتحها؛ صفحة المواد والتذاكر التشغيلية محمية.",
    whatYouNeedToKnow: ["لا توجد قائمة عامة مكتملة تم التحقق منها في هذا البناء.", "المناطق والوقت قد يتغيران، لذلك لا يصح حفظهما من الذاكرة.", "المصدر المرجعي المسجل هو Materiaalisalkku وتحديثات السائق، وكلاهما خلف Extranet عند التحقق."],
    officialProcedure: ["NOT_VERIFIED — راجع Extranet أو تعليمات الشركة المصرح بها.", "لا تستخدم هذه المنصة لإثبات وقت فتح أو إغلاق منطقة."],
    terminology: ["Alue", "Aukeamisaika", "Kuljettajatiedote"],
    commonMistake: "عرض وقت فتح قديم كأنه قاعدة حالية.",
    sourceIds: ["th-materials", "th-driver-notices"],
    evidenceIds: ["e-materials-001", "e-notices-001"],
    lastVerified: verifiedOn,
    status: "not_verified",
  },
  {
    id: "kb-stands-001",
    moduleId: "taxi-stands",
    title: "مواقف التاكسي: القائمة الحية",
    summary: "صفحة Taksiasemat الرسمية هي المرجع المناسب للمواقع الحالية؛ لا ننسخ قائمة ثابتة قد تصبح قديمة.",
    whatYouNeedToKnow: ["الموقع الرسمي يوفر صفحة مخصصة لمواقف التاكسي.", "هذا التطبيق يحفظ رابط المرجع ولا يدعي أن المواقع الحالية ثابتة.", "تعليمات الموقف التعاقدي في Tripla تظهر ضمن خدمات المشغلين، لكن تفاصيل التشغيل ليست درسًا عامًا هنا."],
    officialProcedure: ["افتح قائمة Taksiasemat الرسمية قبل الاعتماد على موقع موقف.", "تحقق من تعليمات الموقف التعاقدي من صفحة الخدمات الحالية.", "لا تستنتج أولوية أو وقت انتظار من اسم الموقف."],
    terminology: ["Taksiasema", "Sopimustaksiasema"],
    commonMistake: "نسخ موقع موقف من منشور قديم دون فتح المصدر الحالي.",
    sourceIds: ["th-taxi-stands", "th-services-drivers"],
    evidenceIds: ["e-service-001"],
    lastVerified: verifiedOn,
    status: "official_current",
  },
  {
    id: "kb-airport-001",
    moduleId: "airport",
    title: "المطار — لا تعليمات انتظار مخترعة",
    summary: "تم اكتشاف صفحة Toiminta lentoasemalla، لكن لم نثبت منها في هذا البناء تعليمات صف أو بوابة أو وقت تشغيل للسائق.",
    whatYouNeedToKnow: ["رابط صفحة المطار الرسمي محفوظ في سجل المصادر.", "لا نستخدم خرائط أو أوقات انتظار من مصادر ثانوية.", "كل إجراء داخلي يحتاج دليلًا رسميًا عامًا أو وصولًا مصرحًا إلى مواد الشركة."],
    officialProcedure: ["NOT_VERIFIED — افتح الصفحة الرسمية أو دليل الشركة المصرح به قبل تنفيذ إجراء مطار.", "لا تعرض هذه المنصة مسارًا تشغيليًا غير موثق."],
    terminology: ["Lentoasema", "Nouto", "Taksiasema"],
    commonMistake: "إعطاء بوابة أو منطقة انتظار من الذاكرة.",
    sourceIds: ["th-airport"],
    evidenceIds: [],
    lastVerified: verifiedOn,
    status: "not_verified",
  },
  {
    id: "kb-ports-001",
    moduleId: "ports",
    title: "الموانئ — فصل الصفحة العامة عن الإجراء الداخلي",
    summary: "صفحة Toiminta satamissa مسجلة، لكن لا نضع تعليمات رصيف أو منطقة انتظار بلا دليل عام قابل للتحقق.",
    whatYouNeedToKnow: ["المصدر الرسمي للموانئ موجود في سجل المصادر.", "المعلومة العامة عن وجود صفحة ليست دليلًا على كل إجراء في الميناء.", "لا تستخدم التطبيق لإثبات وقت فتح أو بوابة أو مسار غير منشور."],
    officialProcedure: ["NOT_VERIFIED — افتح المصدر الرسمي الحالي أو تعليمات الشركة المصرح بها.", "اعرض المصدر بدل ملء الفراغ بتخمين."],
    terminology: ["Satama", "Nouto-osoite", "Alue"],
    commonMistake: "اعتبار تعليمات مطار أو موقف قاعدة للميناء.",
    sourceIds: ["th-ports"],
    evidenceIds: [],
    lastVerified: verifiedOn,
    status: "not_verified",
  },
  {
    id: "kb-kela-001",
    moduleId: "kela",
    title: "Kela: مصدر حالي ومصدر تاريخي",
    summary: "نُظهر إرشادات Kela الحالية منفصلة عن دليل AD KELA المؤرخ 2024 وعن وصف الخدمة التاريخي 2021–2022.",
    whatYouNeedToKnow: ["صفحة Kela الرسمية هي المرجع الحالي لحقوق العميل والحجز عند هذا التحقق.", "دليل AD KELA المؤرخ 2024 مفيد لفهم واجهة تاريخية لكنه يحتاج تحققًا قبل التشغيل.", "وصف الخدمة 2022 سجل تاريخي ولا يعرض كقاعدة 2026."],
    officialProcedure: ["ابدأ من صفحة Kela الحالية.", "افتح دليل Taksi Helsinki الخاص بالمركبة أو التطبيق إذا كان إصدارًا ساريًا ومصرحًا به.", "ضع وسم Historical على المعلومات التي تأتي من الوثائق القديمة."],
    terminology: ["Kela", "Välityskeskus", "Omavastuu", "Tuttu taksinkuljettaja"],
    commonMistake: "استخدام مثال من عقد أو دليل 2022 كأنه إجراء حالي.",
    sourceIds: ["kela-transport", "th-kela", "th-kela-autot", "th-ad-kela-2024", "th-kela-service-description-2022"],
    evidenceIds: ["e-kela-005", "e-kela-current-001", "e-th-kela-001", "e-kela-historical-001"],
    lastVerified: verifiedOn,
    status: "official_current",
  },
  {
    id: "kb-kela-002",
    moduleId: "kela",
    title: "AD KELA التاريخي: الرحلة والبيانات",
    summary: "الدليل التاريخي يثبت مسارًا تفصيليًا للعرض ومراحل الرحلة وربط بيانات العداد، مع تحذير تاريخي واضح.",
    whatYouNeedToKnow: ["الدليل يشرح عرض الطلب ومراحل بدء الرحلة والوصول والاستلام والإنهاء.", "يقول إن بيانات العداد تُربط ببيانات التطبيق عبر معرف الطلب.", "كل هذه النقاط تحمل تحذير Historical؛ لا تعني أنها واجهة 2026 الحالية."],
    officialProcedure: ["اقرأ الإصدار الحالي قبل تطبيق أي زر.", "استخدم معرف الطلب الصحيح فقط إذا أكد الإصدار الحالي ذلك.", "عند اختلاف الشاشة، اتبع الدليل الحالي أو المشرف المصرح به."],
    terminology: ["Matkahistoria", "Tilaustunnus", "Luokseajokorvaus"],
    commonMistake: "استخدام سقف تعويض تاريخي من دليل 2024 كأنه سعر حالي.",
    sourceIds: ["th-ad-kela-2024"],
    evidenceIds: ["e-kela-001", "e-kela-004", "e-kela-005", "e-kela-007"],
    lastVerified: verifiedOn,
    status: "official_historical",
  },
  {
    id: "kb-kela-003",
    moduleId: "kela",
    title: "تشغيل Kela المنشور: Ahola Digital والعدادات",
    summary: "صفحة Taksi Helsinki العامة تشرح طبقة تشغيل Kela الحالية: مناطق العقد، نظام Ahola Digital، أجهزة الإرسال، والعدادات المعتمدة.",
    whatYouNeedToKnow: ["صفحة Kela الحالية تفصل عقد التشغيل حتى 31.12.2026 عن صفحة العقد الجديد التي يبدأ إرسالها في 1.1.2027.", "Taksi Helsinki تقول إن Ahola Digital مستخدم في إحالة الطلبات، ويمكن ربط الإحالة بجهاز موجود أو توفير جهاز إحالة.", "الصفحة الحالية تسرد Cabman MDT وSemel M2 وMitax 300 وMitax 400 كعدادات معتمدة في ذلك السياق."],
    officialProcedure: ["تحقق من منطقة العقد وتاريخها قبل تطبيق معلومة Kela.", "استخدم جهاز الإحالة والعداد وفق الإصدار الرسمي الخاص بالمركبة؛ هذه الصفحة لا تثبت أزرار التشغيل.", "لا تخلط قائمة العدادات الحالية بقائمة العقد الجديد التي تتضمن Mitax 500 من 1.1.2027."],
    terminology: ["Ahola Digital", "Tilausvälityspääte", "Cabman MDT", "Semel M2", "Mitax 300", "Mitax 400"],
    commonMistake: "اعتبار قائمة أجهزة العقد الجديد قاعدة سارية في 2026 أو نقل اسم نظام الإحالة إلى تعليمات Autocab.",
    sourceIds: ["th-kela-autot"],
    evidenceIds: ["e-kela-th-001", "e-kela-th-002"],
    lastVerified: verifiedOn,
    status: "official_current",
  },
  {
    id: "kb-kela-004",
    moduleId: "kela",
    title: "Kela 2027: ما هو مستقبلي وما يجب عدم خلطه بالحاضر",
    summary: "FUTURE — صفحة Taksi Helsinki تفصل بوضوح عقد 2027، الأجهزة المقبولة، متطلبات السائق، وجدول التدريب عن تشغيل 2026.",
    whatYouNeedToKnow: ["الفترة المستقبلية المنشورة هي 1.1.2027–31.12.2030، وتبدأ إحالة العقد الجديد في 1.1.2027.", "المناطق المذكورة للعقد الجديد هي Uusimaa وKanta-Häme وVarsinais-Suomi وEtelä-Karjala وLappi.", "تذكر الصفحة أن تدريب Kela المحدّث يفتح في نوفمبر 2026 استعدادًا لبدء الرحلات في يناير 2027."],
    officialProcedure: ["اعرض هذه المعلومات كـ FUTURE ولا تستخدمها بدل التعليمات الحالية قبل effective_date.", "راجع الأجهزة المستقبلية كما نشرتها الصفحة: Samsung Xcover 5/7 وTab Active 3/5، والعدادات Semel M2 وMitax 300/400/500 وCabman.", "انتبه إلى الفرق بين Toivetaksi (طلب سيارة مفضلة) وحق Kela في سائق مألوف؛ الصفحة تنص على أنهما شيئان مختلفان."],
    terminology: ["Uusi sopimuskausi", "Välityspääte", "Toivetaksi", "Vakiotaksioikeus"],
    commonMistake: "وضع متطلبات أو أجهزة 2027 على أنها تعليمات تشغيل حالية في 2026.",
    sourceIds: ["th-kela-2027"],
    evidenceIds: ["e-kela-future-001", "e-kela-future-002", "e-kela-future-003", "e-kela-future-004"],
    lastVerified: verifiedOn,
    status: "official_future",
  },
  {
    id: "kb-special-001",
    moduleId: "special-transport",
    title: "الرحلات ذات الاحتياجات الخاصة",
    summary: "نستخدم لغة المصادر فقط: احتياجات المركبة، المساعدة، والحق في نوع مركبة لا تتحول إلى تشخيص أو قرار استحقاق من التطبيق.",
    whatYouNeedToKnow: ["مصادر Kela تميز بين الحاجة إلى مركبة يمكن الوصول إليها أو تجهيزات خاصة وبين الرحلة العادية.", "صفحة Taksi Helsinki تذكر تدريب المجموعات الخاصة ضمن مسار السائقين المرتبطين بخدمات Kela.", "لا يقرر التطبيق استحقاق العميل ولا يطلب بيانات صحية."],
    officialProcedure: ["راجع تفاصيل الرحلة والمتطلبات الظاهرة في العرض.", "استخدم المركبة المناسبة فقط عندما تكون متطلبات الطلب أو المصدر المصرح بها واضحة.", "عند غموض أو تعارض، استخدم قناة الخدمة الرسمية؛ لا تستنتج من اسم العميل."],
    terminology: ["Erityisryhmät", "Invataksi", "Paaritaksi", "Avustaminen"],
    commonMistake: "تحويل اسم نوع المركبة إلى حكم طبي أو افتراض احتياج لم يذكره الطلب.",
    sourceIds: ["kela-transport", "th-kela", "th-kela-service-description-2022"],
    evidenceIds: ["e-kela-historical-001"],
    lastVerified: verifiedOn,
    status: "official_current",
  },
  {
    id: "kb-services-001",
    moduleId: "special-services",
    title: "خدمات المشغلين التي تؤثر على عمل السائق",
    summary: "صفحة الخدمات العامة تكتشف فئات مهمة، لكنها لا تجعل نماذج الطلب التجارية دليل تشغيل للرحلة.",
    whatYouNeedToKnow: ["الصفحة تربط إلى Cabman MDT وإلى جهاز الإرسال اللوحي.", "تذكر خدمة السيارة البديلة، بطاقة المرخص له، موقف Tripla التعاقدي، والانضمام إلى إحالة Kela ضمن فئات الخدمات.", "تفاصيل النماذج والعقود ليست درسًا عامًا ولا تُعرض كشرط شخصي للسائق."],
    officialProcedure: ["استخدم صفحة الخدمات للوصول إلى النموذج أو الجهة الصحيحة.", "تحقق من أهلية المشغل والعقد مع Taksi Helsinki مباشرة.", "لا تنقل شرطًا تجاريًا إلى درس سائق دون دليل صريح."],
    terminology: ["Cabman MDT", "Vara-auto", "Luvanhaltijakortti", "Sopimustaksiasema"],
    commonMistake: "اعتبار صفحة خدمة للمشغلين عقدًا أو تعليمات يومية للسائق.",
    sourceIds: ["th-services-drivers"],
    evidenceIds: ["e-service-001"],
    lastVerified: verifiedOn,
    status: "official_current",
  },
  {
    id: "kb-exam-001",
    moduleId: "exam",
    title: "Mock exam مبني على Evidence",
    summary: "الأسئلة الجديدة في هذا البناء مرتبطة برقم Evidence، وتحمل صراحة training_question=true وofficial_exam_question=false.",
    whatYouNeedToKnow: ["أسئلة AD مبنية على صفحات الدليل العام وأرقام صفحاتها.", "أسئلة الجودة مبنية على Kuljettajan laatusitoumus.", "لا يوجد ادعاء بأن هذه الأسئلة من امتحان Taksi Helsinki أو Traficom الحقيقي."],
    officialProcedure: ["أجب من النص المرتبط بالمصدر.", "افتح Evidence عند الخطأ بدل حفظ الاختيار فقط.", "تحقق من المصدر إذا تغير الإصدار أو التاريخ."],
    terminology: ["Evidence", "Training question", "Official exam question"],
    commonMistake: "تسمية سؤال تدريبي سؤال امتحان حقيقي.",
    sourceIds: ["th-ad-sote-2026", "th-quality-commitment", "traficom-licence"],
    evidenceIds: ["e-ad-001", "e-ad-006", "e-quality-002"],
    lastVerified: verifiedOn,
    status: "official_current",
  },
];

export const knowledgeGlossary: KnowledgeGlossaryEntry[] = [
  { term: "Ajotarjous", meaning: "عرض رحلة", explanation: "العرض الذي يعرض للسائق بيانات الرحلة قبل القبول أو الرفض.", example: "Tarkista ajotarjous ennen hyväksymistä. · تحقق من عرض الرحلة قبل القبول.", sourceLabel: "AD Kuljettaja SOTE · p. 8", sourceIds: ["th-ad-sote-2026"], evidenceId: "e-ad-005" },
  { term: "Työvuoro", meaning: "الوردية", explanation: "وقت العمل المحفوظ داخل تطبيق السائق.", example: "Tallenna työvuoro ennen tarjouksia. · احفظ الوردية قبل انتظار العروض.", sourceLabel: "AD Kuljettaja SOTE · p. 6", sourceIds: ["th-ad-sote-2026"], evidenceId: "e-ad-003" },
  { term: "Varattuna", meaning: "مشغول / محجوز", explanation: "حالة لا يتلقى فيها السائق عروض الرحلات وفق دليل AD الحالي.", example: "Olet varattuna etkä saa ajotarjouksia. · أنت في حالة مشغول ولا تصلك عروض.", sourceLabel: "AD Kuljettaja SOTE · p. 7", sourceIds: ["th-ad-sote-2026"], evidenceId: "e-ad-004" },
  { term: "Avoimet", meaning: "الطلبات المفتوحة", explanation: "قائمة الطلبات التي لم تجد سيارة ويمكن ترتيبها بالوقت أو المسافة.", example: "Avoimet-listalla on vapaita poimittavia tilauksia. · توجد طلبات قابلة للاختيار في القائمة المفتوحة.", sourceLabel: "AD Kuljettaja SOTE · p. 13", sourceIds: ["th-ad-sote-2026"], evidenceId: "e-ad-007" },
  { term: "Ruudut", meaning: "المربعات / مناطق الطابور", explanation: "عرض يعرض معلومات المربعات والمرشحات وقيم الطابور في دليل AD.", example: "Tarkastele ruutuja ja valitse suodatin. · راجع المربعات واختر المرشح.", sourceLabel: "AD Kuljettaja SOTE · p. 15–16", sourceIds: ["th-ad-sote-2026"], evidenceId: "e-ad-008" },
  { term: "Saavuin paikalle", meaning: "وصلت إلى المكان", explanation: "حالة رحلة يذكرها الدليل عند الوصول إلى نقطة الاستلام أو الوجهة.", example: "Paina Saavuin paikalle noutopaikassa. · اضغط وصلت إلى المكان عند الاستلام.", sourceLabel: "AD Kuljettaja SOTE · p. 9–12", sourceIds: ["th-ad-sote-2026"], evidenceId: "e-ad-006" },
  { term: "Nouto valmis", meaning: "اكتمل الاستلام", explanation: "الحالة التي يذكرها الدليل بعد ركوب العميل.", example: "Kun asiakas on kyydissä, valitse Nouto valmis. · بعد ركوب العميل اختر اكتمل الاستلام.", sourceLabel: "AD Kuljettaja SOTE · p. 10", sourceIds: ["th-ad-sote-2026"], evidenceId: "e-ad-006" },
  { term: "Määränpää valmis", meaning: "اكتملت الوجهة", explanation: "حالة إنهاء الرحلة بعد مغادرة العميل أو مساعدته إلى الوجهة وفق الدليل الحالي.", example: "Valitse Määränpää valmis matkan lopussa. · اختر اكتملت الوجهة في نهاية الرحلة.", sourceLabel: "AD Kuljettaja SOTE · p. 11", sourceIds: ["th-ad-sote-2026"], evidenceId: "e-ad-006" },
  { term: "Matkahistoria", meaning: "تاريخ الرحلات", explanation: "قائمة الرحلات السابقة التي يمكن البحث فيها حسب الوردية أو التاريخ.", example: "Tarkista matka Matkahistoriasta. · راجع الرحلة من تاريخ الرحلات.", sourceLabel: "AD Kuljettaja SOTE · p. 17", sourceIds: ["th-ad-sote-2026"], evidenceId: "e-ad-009" },
  { term: "Vaitiolovelvollisuus", meaning: "واجب السرية", explanation: "التزام وارد في وثيقة الجودة لحماية خصوصية العميل.", example: "Noudata vaitiolovelvollisuutta. · التزم بواجب السرية.", sourceLabel: "Kuljettajan laatusitoumus · p. 4–5", sourceIds: ["th-quality-commitment"], evidenceId: "e-quality-006" },
  { term: "Kuljettajakortti", meaning: "بطاقة السائق", explanation: "بطاقة يجب أن تكون ظاهرة للعميل وفق التزام الجودة.", example: "Pidä kuljettajakortti näkyvillä. · أبقِ بطاقة السائق ظاهرة.", sourceLabel: "Kuljettajan laatusitoumus · p. 2", sourceIds: ["th-quality-commitment"], evidenceId: "e-quality-002" },
  { term: "Luokseajokorvaus", meaning: "تعويض الوصول إلى العميل", explanation: "مصطلح موجود في دليل Kela التاريخي، ولا يعرض هنا كقيمة حالية.", example: "Tarkista aina voimassa oleva ohje. · تحقق دائمًا من التعليمات السارية.", sourceLabel: "AD Kuljettaja KELA · historical p. 16–17", sourceIds: ["th-ad-kela-2024"], evidenceId: "e-kela-007" },
];

export const knowledgeQuestions: KnowledgeQuestion[] = [
  { id: "kb-q-001", category: "AD Kuljettaja", finnish: "Mitä tapahtuu, jos AD Kuljettaja on taustalla tai näppäinlukko on käytössä?", arabic: "ما الخطر الذي يذكره دليل AD عند إبقاء التطبيق في الخلفية أو استخدام قفل المفاتيح؟", options: ["قد لا تصل عروض الرحلات", "تتغير لغة التطبيق فقط", "تُحفظ الرحلة تلقائيًا", "لا يحدث شيء"], answer: 0, explanation: "يذكر دليل 02.02.2026 أن التطبيق يجب أن يبقى في المقدمة وأن الخلفية أو قفل المفاتيح قد يمنعان وصول العروض.", source: "Taksi Helsinki · Kuljettajaohje 02.02.2026", sourcePage: "2", evidenceId: "e-ad-001", trainingQuestion: true, officialExamQuestion: false },
  { id: "kb-q-002", category: "AD Kuljettaja", finnish: "Saako kuljettaja ajotarjouksia Varattuna-tilassa?", arabic: "هل يتلقى السائق عروضًا في حالة Varattuna؟", options: ["نعم دائمًا", "لا، لا يتلقى عروض القيادة", "فقط في الليل", "فقط من Avoimet-lista"], answer: 1, explanation: "الدليل الحالي يقول إن السائق في حالة Varattuna لا يحصل على عروض، وعليه العودة إلى Olet ajossa عند التفرغ.", source: "Taksi Helsinki · Kuljettajaohje 02.02.2026", sourcePage: "7", evidenceId: "e-ad-004", trainingQuestion: true, officialExamQuestion: false },
  { id: "kb-q-003", category: "AD Kuljettaja", finnish: "Mikä tieto kuuluu ajotarjouksen pääkohtiin?", arabic: "أي معلومة تظهر ضمن النقاط الرئيسية لعرض الرحلة؟", options: ["Nouto- ja kohdeosoite", "كلمة مرور السائق", "رقم بطاقة العميل البنكية", "تقييم سري"], answer: 0, explanation: "الدليل يذكر وقت الاستلام وعناوين الاستلام والوجهة وتقدير السعر والمتطلبات الخاصة ضمن العرض.", source: "Taksi Helsinki · Kuljettajaohje 02.02.2026", sourcePage: "8", evidenceId: "e-ad-005", trainingQuestion: true, officialExamQuestion: false },
  { id: "kb-q-004", category: "AD Kuljettaja", finnish: "Mikä on yksi matkan vaiheista asiakkaan ollessa kyydissä?", arabic: "ما الحالة التي يستخدمها السائق بعد ركوب العميل؟", options: ["NOUTO VALMIS", "POISTA KAIKKI", "LISÄÄ SALASANA", "SULJE KAIKKI"], answer: 0, explanation: "يذكر الدليل اختيار NOUTO VALMIS عندما يكون العميل داخل السيارة.", source: "Taksi Helsinki · Kuljettajaohje 02.02.2026", sourcePage: "10", evidenceId: "e-ad-006", trainingQuestion: true, officialExamQuestion: false },
  { id: "kb-q-005", category: "AD Kuljettaja", finnish: "Miten Avoimet-listaa voi järjestää?", arabic: "كيف يمكن ترتيب قائمة Avoimet؟", options: ["بالوقت أو المسافة", "باللون فقط", "حسب اسم العميل فقط", "لا يمكن ترتيبها"], answer: 0, explanation: "صفحة Avoimet في الدليل تذكر الترتيب الزمني أو حسب المسافة.", source: "Taksi Helsinki · Kuljettajaohje 02.02.2026", sourcePage: "13", evidenceId: "e-ad-007", trainingQuestion: true, officialExamQuestion: false },
  { id: "kb-q-006", category: "AD Kuljettaja", finnish: "Mitä UUID-tiedon avulla voidaan tarvittaessa tehdä?", arabic: "في ماذا يمكن استخدام UUID عند الحاجة؟", options: ["طلب تصحيح الفوترة", "فتح حساب بنكي", "تغيير رخصة القيادة", "حذف المصدر"], answer: 0, explanation: "يذكر الدليل أن UUID الموجود في بيانات الرحلة يساعد عند الحاجة إلى طلب تصحيح للفوترة.", source: "Taksi Helsinki · Kuljettajaohje 02.02.2026", sourcePage: "17", evidenceId: "e-ad-009", trainingQuestion: true, officialExamQuestion: false },
  { id: "kb-q-007", category: "الجودة", finnish: "Mitä kuljettajakortille tulee tehdä?", arabic: "ما المطلوب من بطاقة السائق؟", options: ["إبقاؤها ظاهرة للعميل", "إخفاؤها دائمًا", "إرسالها للعميل بعد شهر", "لا علاقة لها بالعميل"], answer: 0, explanation: "التزام الجودة يقول إن بطاقة السائق يجب أن تكون ظاهرة بحيث يراها العميل بسهولة.", source: "Taksi Helsinki · Kuljettajan laatusitoumus", sourcePage: "2", evidenceId: "e-quality-002", trainingQuestion: true, officialExamQuestion: false },
  { id: "kb-q-008", category: "الجودة", finnish: "Mitä kuljettajan tulee tarjota asiakkaalle maksun jälkeen?", arabic: "ماذا يجب أن يعرض السائق للعميل بعد الدفع؟", options: ["إيصالًا، بما في ذلك عند الدفع نقدًا", "كلمة مرور التطبيق", "تقييمًا إجباريًا", "لا شيء"], answer: 0, explanation: "وثيقة الجودة تذكر عرض الإيصال للعميل، بما في ذلك الدفع النقدي.", source: "Taksi Helsinki · Kuljettajan laatusitoumus", sourcePage: "3–4", evidenceId: "e-quality-005", trainingQuestion: true, officialExamQuestion: false },
  { id: "kb-q-009", category: "الخصوصية", finnish: "Milloin kuljettaja saa käyttää puhelinta asiakkaan ollessa kyydissä?", arabic: "متى يجوز للسائق استخدام الهاتف أثناء وجود العميل؟", options: ["لأمور مرتبطة مباشرة بالرحلة فقط", "لأمور شخصية طوال الرحلة", "لتصوير العميل", "لا توجد قاعدة"], answer: 0, explanation: "وثيقة الجودة تمنع استخدام الهاتف للأمور غير المرتبطة بالرحلة أثناء وجود العميل.", source: "Taksi Helsinki · Kuljettajan laatusitoumus", sourcePage: "4–5", evidenceId: "e-quality-006", trainingQuestion: true, officialExamQuestion: false },
  { id: "kb-q-010", category: "مصدر مقيد", finnish: "Onko julkinen Autocab-ohje vahvistettu tässä tietokannassa?", arabic: "هل تم التحقق من دليل Autocab عام في قاعدة المعرفة؟", options: ["نعم، وهو مصدر حالي", "لا، المصدر خلف تسجيل الدخول أو غير مكشوف للعامة", "نعم، من Reddit", "لا نحتاج مصدرًا"], answer: 1, explanation: "سجل المصادر يوضح أن مدخل Materiaalisalkku الرسمي يعيد التوجيه إلى Extranet؛ لذلك لا نثبت إجراءات Autocab التشغيلية.", source: "Taksi Helsinki · Materiaalisalkku entry point", sourcePage: "login page", evidenceId: "e-materials-001", trainingQuestion: true, officialExamQuestion: false },
];

export const mockExams = [
  { id: "mock-driver", title: "Mock 1 · Driver basics", description: "الجهاز، الدخول، الوردية، والعروض.", questionIds: ["kb-q-001", "kb-q-002", "kb-q-003"] },
  { id: "mock-trip", title: "Mock 2 · Trip workflow", description: "مراحل الرحلة وقائمة Avoimet وتاريخ الرحلات.", questionIds: ["kb-q-004", "kb-q-005", "kb-q-006"] },
  { id: "mock-quality", title: "Mock 3 · Quality and privacy", description: "البطاقة، الإيصال، الهاتف والخصوصية.", questionIds: ["kb-q-007", "kb-q-008", "kb-q-009"] },
  { id: "mock-source", title: "Mock 4 · Source literacy", description: "تمييز الإجراء الموثق عن المادة المقيدة.", questionIds: ["kb-q-010"] },
  { id: "mock-mixed", title: "Mock 5 · Full verified mix", description: "تجميعة صغيرة من الأسئلة الجديدة المرتبطة بالأدلة.", questionIds: knowledgeQuestions.map((question) => question.id) },
];

const sourceStatusCount = (status: SourceStatus) => sourceRegistry.filter((source) => source.status === status).length;

export const knowledgeAudit = {
  officialSourcesDiscovered: sourceRegistry.filter((source) => source.official).length,
  officialPdfsDiscovered: sourceRegistry.filter((source) => source.documentType.toLowerCase().includes("pdf")).length,
  officialPdfsParsed: sourceRegistry.filter((source) => source.documentType.toLowerCase().includes("pdf") && source.parsed).length,
  currentSources: sourceStatusCount("official_current"),
  historicalSources: sourceStatusCount("official_historical"),
  futureSources: sourceStatusCount("official_future"),
  restrictedSources: sourceStatusCount("access_restricted"),
  knowledgeClaims: evidenceRegistry.length,
  lessonsGenerated: knowledgeLessons.length,
  practicalScenarios: knowledgeLessons.filter((lesson) => lesson.scenario).length,
  quizQuestions: knowledgeQuestions.length,
  sourcesWithScreenshots: 0,
  unverifiedClaims: 0,
  notVerifiedTopics: knowledgeModules.filter((module) => module.status === "not_verified").length,
  lastVerified: verifiedOn,
};

export function sourceFor(id: string) {
  return sourceRegistry.find((source) => source.id === id);
}

export function evidenceFor(id: string) {
  return evidenceRegistry.find((evidence) => evidence.id === id);
}
